# .github/workflows/deploy.yml
name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd frontend
        npm ci
    
    - name: Run tests
      run: |
        npm test
        cd frontend
        npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Build application
      run: |
        npm ci
        cd frontend
        npm ci
        npm run build
    
    - name: Build Docker image
      run: |
        docker build -t guimashan-staff-schedule:latest -f deploy/docker/Dockerfile .
    
    - name: Save Docker image
      run: |
        docker save guimashan-staff-schedule:latest -o guimashan-staff-schedule.tar
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: guimashan-staff-schedule.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download Docker image
      uses: actions/download-artifact@v3
      with:
        name: docker-image
    
    - name: Load Docker image
      run: |
        docker load -i guimashan-staff-schedule.tar
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker stop guimashan-app || true
          docker rm guimashan-app || true
          docker rmi guimashan-staff-schedule:latest || true
          docker load -i guimashan-staff-schedule.tar
          docker run -d --name guimashan-app -p 3001:3001 guimashan-staff-schedule:latest
          docker system prune -f
